# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /var/home/Dodo/Linux_Unreal_Engine_5.5.3

TARGETS = \
	RTS-Android-DebugGame  \
	RTS-Android-Development  \
	RTS-Android-Shipping  \
	RTS-Linux-DebugGame  \
	RTS-Linux-Development  \
	RTS-Linux-Shipping  \
	RTS-LinuxArm64-DebugGame  \
	RTS-LinuxArm64-Development  \
	RTS-LinuxArm64-Shipping  \
	RTS \
	RTSEditor-Linux-DebugGame  \
	RTSEditor-Linux-Development  \
	RTSEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend RTSEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug RTSEditor-Linux-Debug


RTS-Android-DebugGame:
	 $(BUILD) RTS Android DebugGame  -Project="/home/Dodo/Documents/Unreal Projects/RTS/RTS.uproject" $(ARGS)

RTS-Android-Development:
	 $(BUILD) RTS Android Development  -Project="/home/Dodo/Documents/Unreal Projects/RTS/RTS.uproject" $(ARGS)

RTS-Android-Shipping:
	 $(BUILD) RTS Android Shipping  -Project="/home/Dodo/Documents/Unreal Projects/RTS/RTS.uproject" $(ARGS)

RTS-Linux-DebugGame:
	 $(BUILD) RTS Linux DebugGame  -Project="/home/Dodo/Documents/Unreal Projects/RTS/RTS.uproject" $(ARGS)

RTS-Linux-Development:
	 $(BUILD) RTS Linux Development  -Project="/home/Dodo/Documents/Unreal Projects/RTS/RTS.uproject" $(ARGS)

RTS-Linux-Shipping:
	 $(BUILD) RTS Linux Shipping  -Project="/home/Dodo/Documents/Unreal Projects/RTS/RTS.uproject" $(ARGS)

RTS-LinuxArm64-DebugGame:
	 $(BUILD) RTS LinuxArm64 DebugGame  -Project="/home/Dodo/Documents/Unreal Projects/RTS/RTS.uproject" $(ARGS)

RTS-LinuxArm64-Development:
	 $(BUILD) RTS LinuxArm64 Development  -Project="/home/Dodo/Documents/Unreal Projects/RTS/RTS.uproject" $(ARGS)

RTS-LinuxArm64-Shipping:
	 $(BUILD) RTS LinuxArm64 Shipping  -Project="/home/Dodo/Documents/Unreal Projects/RTS/RTS.uproject" $(ARGS)

RTS: RTS-Linux-Development

RTSEditor-Linux-DebugGame:
	 $(BUILD) RTSEditor Linux DebugGame  -Project="/home/Dodo/Documents/Unreal Projects/RTS/RTS.uproject" $(ARGS)

RTSEditor-Linux-Development:
	 $(BUILD) RTSEditor Linux Development  -Project="/home/Dodo/Documents/Unreal Projects/RTS/RTS.uproject" $(ARGS)

RTSEditor: RTSEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/Dodo/Documents/Unreal Projects/RTS/RTS.uproject" -Game 

.PHONY: $(TARGETS)
